name: 15 Workking with Matrices
run-name: Matrix Job Example
on:
    workflow_dispatch:
jobs:
  backward-compatibility:
    name:  ${{ matrix.os }} - Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        echo "Installing dependencies on ${{ matrix.os }} with Node.js ${{ matrix.node-version }}"
        
