name: Custom Action
run-name: Custom Action Workflow
on:
    workflow_dispatch:
jobs:
  custom_job:
    runs-on: ubuntu-latest
    steps:
    - name: Steup Node and NPM dependencies
      uses: ./.github/actions/composite-cache-deps
      with:
        node-version: '20.x'
        working-dir:  ./react-app

   